name: action
on:
  workflow_dispatch:
  schedule:
    - cron: '24 */4 * * *'
jobs:
  pkg_compare:
    runs-on: ubuntu-latest
    steps:
    - id: pkg_compare
      env:
        MSYS2_DB_LAST_MODIFIED: ${{ secrets.MSYS2_DB_LAST_MODIFIED }}
      run: |
          touch -d @${MSYS2_DB_LAST_MODIFIED} msys.db.tar.gz
          wget -N https://repo.msys2.org/msys/x86_64/msys.db.tar.gz
          if [ "$MSYS2_DB_LAST_MODIFIED" -lt "$(stat -c '%Y' msys.db.tar.gz)" ]; then
            touch -d @${MSYS2_DB_LAST_MODIFIED} ref
            rm -rf t
            mkdir t && tar -C t -zxf msys2.db.tar.gz
            find t -mindepth 1 -maxdepth 1 -newer ref -printf "%T@\t%Tc\t%P\n" | sort -n | cut -f 2-
          fi
          echo "::set-output name=msys2_db_last_modified::$(stat -c '%Y' msys.db.tar.gz)"
    - uses: jeremyd2019/store-secret@v1
      env:
        GITHUB_TOKEN: ${{ secrets.STORE_SECRETS_PAT }}
      with:
        name: MSYS2_DB_LAST_MODIFIED
        value: ${{ steps.pkg_compare.outputs.msys2_db_last_modified }}
 
